import Head from 'next/head'
import { Fragment } from 'react'
import Hero from '../components/home-page/hero'

export default function HomePage() {
  return (
    <Fragment>
      <Head>
        <title>Johnatan Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      {/* <FeaturedPosts /> */}

    </Fragment>
  )
}
